# Generated by Django 2.1.3 on 2018-11-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='radio',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
