# Generated by Django 2.1.3 on 2018-11-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20181112_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='date',
        ),
        migrations.AddField(
            model_name='program',
            name='end',
            field=models.DateTimeField(auto_now=True, verbose_name='end date time'),
        ),
        migrations.AddField(
            model_name='program',
            name='start',
            field=models.DateTimeField(auto_now=True, verbose_name='start date time'),
        ),
    ]
