# Generated by Django 2.1.3 on 2018-11-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20181112_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='ptype',
            field=models.IntegerField(choices=[(1, 'Politica'), (2, 'Futebol'), (3, 'Saude')], default=1),
        ),
    ]
